import type { Metadata } from "next";
import Header from "./components/Header";
import {Cormorant,Inter, Geist } from 'next/font/google'

import "./globals.css";
import { cn } from "@/src/app/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const cormorant = Cormorant({ 
  subsets: ['latin'],
  variable: '--font-cormorant',
  weight: ['300', '400', '500', '600', '700']
})
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(cormorant.variable, inter.variable, "font-sans", geist.variable)}>
      <body className="antialiased">
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
